import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/shared/Navbar'
import { neueMontreal } from '@/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${neueMontreal.variable} bg-black min-h-screen flex flex-col text-foreground`}
      >
        <Navbar />
        <main className='pt-20 flex-1'>{children}</main>
      </body>
    </html>
  )
}
